Error in <TKey::ReadObjWithBuffer>: Unknown class -h.ôYƒ[ÍQfÇ>ıÈ8\˚LjGÿî‡¥…#á(ß€ÛY∏R·“TVî'è‹ˆzusxjDH\`ﬂpÇ⁄·À.Á:˛≠&íË¯°H¢)/•Ã ∏JD–¶üÃ£‚ºı=ºitº€,ç>`ùùCÅq‹ ç£*ﬂ•a¡ãÚaPâ≈j†éÙvÕØºÙªÊù$ ∫
Info in <TFile::GetStreamerInfoList>: cannot find the StreamerInfo record in file /eos/user/t/tcritchl/xgBOOST/testing10/test_background_total.root
Traceback (most recent call last):
  File "/afs/cern.ch/work/t/tcritchl/FCCAnalyses_local/xgboost/new_variables_training/20GEV_filter/testing_macro.py", line 342, in <module>
    existing_results = json.load(json_file)
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-centos7-gcc11-opt/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-centos7-gcc11-opt/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-centos7-gcc11-opt/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-centos7-gcc11-opt/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 30953 column 10 (char 524287)
