Traceback (most recent call last):
  File "DataPreparation_macro.py", line 3, in <module>
    import ROOT
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Fri/x86_64-centos7-gcc11-opt/lib/ROOT/__init__.py", line 25, in <module>
    import cppyy
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Fri/x86_64-centos7-gcc11-opt/lib/cppyy/__init__.py", line 71, in <module>
    from ._cpython_cppyy import *
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Fri/x86_64-centos7-gcc11-opt/lib/cppyy/_cpython_cppyy.py", line 18, in <module>
    c = loader.load_cpp_backend()
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Fri/x86_64-centos7-gcc11-opt/lib/cppyy_backend/loader.py", line 62, in load_cpp_backend
    ensure_precompiled_header()
  File "/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Fri/x86_64-centos7-gcc11-opt/lib/cppyy_backend/loader.py", line 109, in ensure_precompiled_header
    olddir = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
