Traceback (most recent call last):
  File "/afs/cern.ch/work/t/tcritchl/FCCAnalyses_local/xgboost/xgboost_batch/testing_macro.py", line 20, in <module>
    sgl_norm = config["signal_normalisation_factor"]
KeyError: 'signal_normalisation_factor'
